# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b9fd52edbcb900e203d6f803935f1461a2c506ee2fd3af999d13be356f38951f367a0e2b47e13a6515d8e65ca895b400220d9697ee660e55da5cce72d0aef5b

test:
  secret_key_base: f7ae6ac7323e725ca22e1a2702f7215bc3d9351ead61ac14feec45d336cbe3652df4d0322c7a1c3cbaabf9a1fa474e9d7b7a9cb87a4276deca1a68d4853900f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
